const { required } = require("joi");
const mongoose = require("mongoose");
const Schema = mongoose.Schema;
const passportLocalMongoose = require("passport-local-mongoose");

// username will be generated by mongoose
const userSchema = new Schema({
    email:{
        type:String,
        required:true
    }
})

userSchema.plugin(passportLocalMongoose);// it will generate username ,hashing ,salting,& hashpassword

module.exports =  mongoose.model('User',userSchema);